### ISSUE TITLE
Positioning elements

### ISSUE THREAD

**Issue by vavroom** [Nic-Slides/Test#1]
Hey Chris,

Thanks for having a look. Here's what I'm trying to accomplish:

<img width="926" alt="Screenshot of a slide" src="https://user-images.githubusercontent.com/29165258/115487804-4a9d5980-a20e-11eb-8c7f-cc5064e64c79.png">

This is a screenshot from one of my slide "as is" from Keynote.

Here's the slide I'm trying to work to get as close to that as possible (never mind fonts right now).

https://nic-slides.github.io/Test/#/5

<img width="1371" alt="Screenshot of a slide" src="https://user-images.githubusercontent.com/29165258/115488639-b59b6000-a20f-11eb-8344-85614a18dee1.png">

Things I'd like to happen:

* Position the heading higher on the viewport
* Position the paragraph lower in the viewport
* Extend the backround of the elements all the way across the browser window (although what I've done will be ok).

Ideally, if a solution is found for that, I'd like to be able to replicate to get better control and using different classes to pop things in different places. For example, I'm using `.img-bg` class and `right` class on the paragraph to give it the background and right text align. I'd probably use different classes to be able to have the heading at the very top, or 10% down, or 20% down, etc.  But first, getting it working at all :D 

You'll see that my reveal.js is loaded as a submodule - which means I have less direct control on some things, but the advantages are great!

You'll also see I'm using Marcy Sutton's accessibility plugin :) 

Anyway, hope you've got enough info to get going.

**Comment by chrisdemars** [comment]
Taking a crack at this! I think we can make something happen.

**Comment by digilou** [comment]
Fixed by creating a `flex-apart` class and adding to helper.js when a `div.accessibilityWrapper` is added around `h2` and `p`.
